### ISSUE TITLE
Hipchat configuration example

### ISSUE THREAD

**Issue by sc0rp10** [AcalephStorage/consul-alerts#103]
Hello!
How can I setup alerting via hipchat?
I tried
```
enabled: true
from: consul
room-id: consul (room exists)
auth-token: <my valid auth token with full admin rights>
```
This doesn't work.

I tried
```
enabled: true
from: consul
room-id: consul (room exists)
auth-token: <my valid auth token with full admin rights>
base-url: https://api.hipchat.com/v2/
```
this also doesn't work
I tried:
```
enabled: true
from: consul
room-id: consul (room exists)
auth-token: <my valid auth token with full admin rights>
base-url: https://my.own.website/
```
and I enabled POST-data logging. My server received next JSON:
```
{
    "color": "red",
    "message": "Consul-Alerts is CRITICAL.\n\nFail: 1, Warn: 0, Pass: 0\n\ndb-profile-stage:redis-profile-stage:Service 'redis-profile-stage' check is critical.\n",
    "notify": true
}
```
Here is no auth token given and Hipchat API returns 401.
BTW, I didn't see any log messages about failed notification and for problem reproduction I doing huge research with request capturing etc.
I think, logs must be more clear.

**Comment by sc0rp10** [comment]
anyone?

**Comment by graemedavidson** [comment]
quick glance and only difference through sets of configurations is to add '/v2/' to base-url with your own site and instead of using room name (i.e. 'consul') and find the room id via the hipchat site.

end url should look like something below which can be used with curl to test.

`https://<<site>>.hipchat.com/v2/room/<<room/api id>>/notification?auth_token=<<token>>`

**Comment by matthewlowry** [comment]
For rooms hosted on their servers, you can omit the `base-url` setting. For my team we just have:
```
enabled: true
room-id: blah
auth-token: blah
cluster-name: blah
```
and it works fine.
You don't need to specialise the base URL with your site/team name.

That said, I'm suprised `base-url: https://api.hipchat.com/v2/` didn't work for you since that's the default and is working for me.

**Comment by sc0rp10** [comment]
Thanks you, @matthewlowry!
I did some research and found, that token must be room token, not global. If you want to get it, you should go to room admin https://<COMPANY>.hipchat.com/rooms/tokens/<ROOM_ID> and create token here.
Common tokens from https://<COMPANY>.hipchat.com/admin/api won't work in this case.
