### ISSUE TITLE
Consul 1.0 compatibility

### ISSUE THREAD

**Issue by nh2** [AcalephStorage/consul-alerts#226]
Hi, is this package known to work with Consul 1.0?

At https://github.com/NixOS/nixpkgs/pull/35602 we're planning to upgrade to Consul 1.0 so we're trying to gather a list of packaged software that might break.

Thanks!

**Comment by Gerrrr** [comment]
Hey @nh2,

TBH I do not really know because we are still running Consul 0.7.5 in production. I am going to add later versions to the [Travis test matrix](https://github.com/AcalephStorage/consul-alerts/blob/master/.travis.yml) and also test manually on the weekend or in the beginning of the next week.

Best,
Aleks

**Comment by nh2** [comment]
Thanks, appreciated!

**Comment by Gerrrr** [comment]
Hi @nh2 

I opened a MR with end-to-end tests for Consul versions from 0.6.4 to 1.0.6 (see #228). 

Seems working :)

Let me know if you have any more questions or concerns.

**Comment by nh2** [comment]
@Gerrrr That's great, thanks a lot! I'll communicate the info that consul-alerts works fine with Consul 1.0 back to where I'm coming from.

Thanks for the effort!
