### ISSUE TITLE
Question: how many consul-alerts instances should be running

### ISSUE THREAD

**Issue by rudijs** [AcalephStorage/consul-alerts#36]
Hi,

I have consul-alerts up and running OK, very pleased!

I'm quite new to Consul so still figuring out the finer details and best practices.

One question I have is how many instances of consul-alerts should be running?

In my case I have a 7 node cluster.

3 x consul servers (key/value)
4 x consul clients

Each client is running the UI web admin.

All 7 consul instance run a mix of custom service/checks and nagios plugin checks.

Should consul-alerts run on:

a) all 7 nodes
b) the 4 client nodes
c) the 3 server nodes
d) single instance?
e) something else?

Any advice here or suggestions would be much appreciated.

If I'm on the wrong track altogether with my consul architecture do please point that out.

Thanks!

**Comment by darkcrux** [comment]
You can run consul-alerts on a single node or for high availability, you can run it on several nodes. consul-alerts can run as a cluster and does leader-election, the leader will be the one that dispatches the alerts while the others on standby. If the node of the consul-alerts leader fails, another consul-alerts instance on different nodes will take the role.

You can run it on all 7 nodes. I suggest just running it with the 3 server nodes unless those nodes are already heavy loaded. If all server nodes are down, consul-alerts won't work too since it relies on a working consul cluster (currently it crashes... need to fix it).

**Comment by rudijs** [comment]
@darkcrux OK great, thanks for taking the time to tap that out.

I have it on all 7 nodes right now, but I think I'll scale down go with the 3 server nodes only.

If load becomes and issue I'll shuffle things around.

I'm very happy with Consul and Consul-alerts, I'll be following this project and will keep any eye out for bug fixes and upgrades.

I'm mostly a node.js and Ruby dev (currently), but using Consul has encouraged me to pick up my 1st Go book and learn the language.

If I'm ever able to actively contribute I will.

Thanks!

**Comment by rudijs** [comment]
@darkcrux Ah, one question:

> If the node of the consul-alerts leader fails, another consul-alerts instance on different nodes will take the role.

In that case there needs to be more than 2 consul-alerts nodes running correct?

If a 3 node consul-alerts cluster drops to 2 a new leader cannot be elected (thus no alert sent) ?

**Comment by darkcrux** [comment]
Nah. It should be alright. consul-alerts only requires at least 1 instance. If a 3 node drops to two, one of the two remaining nodes will become the leader.

**Comment by rudijs** [comment]
Ah that's nice. All good then.

Cheers.
